# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2ab86f9e8aaca93c9542f2dad10db7f1998ba6c601c32954590652d8d152681969421d1210ef1d35acd8cf6eae70f5afa4a50aa8751397357cd9ec9d157a88

test:
  secret_key_base: 43e251cc5c7388f14f303bf7e03b1a47c124fc5ade79b4f4f2be6eee12263ca3316c5c3ecf14a3936ece851851a94e90d8df39be13e5621789035a91e4227ae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
